package br.edu.mackenzie.gerenciadornomes;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.io.IOException;
// Import de Banco de Dados JDBC
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class GerenciadorNomesApplication implements CommandLineRunner {

    public static void main(String[] args) {
        SpringApplication.run(GerenciadorNomesApplication.class, args);
    }

    @Override
    public void run(String... args) {
        
        String arquivoEntrada = "access_grande.log";
        String arquivoSaida = "relatorio.txt";

        ManipuladorArquivo manipulador = new ManipuladorArquivo();
        AnalisadorLog analisador = new AnalisadorLog();

        String url = "jdbc:h2:file:./data/analises";
        String usuario = "admin";
        String senha = "admin";

        try {

            List<String> linhas =
                    manipulador.lerLinhas(arquivoEntrada);

            int totalValidos =
                    analisador.contarRegistrosValidos(linhas);

            List<String> falhas =
                    analisador.listarRequisicoesComFalha(linhas);

            double media =
                    analisador.calcularTempoMedioPayments(linhas);

            List<String> relatorio = new ArrayList<>();

            relatorio.add("RELATORIO DE ANALISE DO SERVIDOR");
            relatorio.add("================================");
            relatorio.add(
                    "Registros validos processados: " + totalValidos
            );
            relatorio.add(
                    "Requisicoes com falha: " + falhas.size()
            );

            relatorio.add("");
            relatorio.add("FALHAS ENCONTRADAS");

            for (String falha : falhas) {
                relatorio.add(falha);
            }

            relatorio.add("");
            relatorio.add("TEMPO MEDIO - /api/v1/payments");

            if (media == -1) {
                relatorio.add(
                        "Nao ha dados suficientes para calcular a media."
                );
            } else {
                relatorio.add(
                        String.format("%.2fms", media)
                );
            }

            manipulador.escreverLinhas(
                    arquivoSaida,
                    relatorio
            );

            System.out.println("Relatorio gerado com sucesso.");

            // Conexao com o banco
            try (Connection connection =
                         DriverManager.getConnection(
                                 url,
                                 usuario,
                                 senha
                         );
                 Statement statement =
                         connection.createStatement()) {

                // Cria a tabela caso ela ainda nao exista
                statement.execute("""
                    CREATE TABLE IF NOT EXISTS analises (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        arquivo VARCHAR(500) NOT NULL,
                        registros_validos INT NOT NULL,
                        quantidade_falhas INT NOT NULL,
                        tempo_medio_payments DOUBLE NOT NULL
                    )
                    """);

                RepositorioAnalisesBD repositorio =
                        new RepositorioAnalisesBD(connection);

                // Salva a analise atual
                repositorio.salvar(
                        arquivoEntrada,
                        totalValidos,
                        falhas.size(),
                        media
                );

                // Consulta o historico
                System.out.println("\nHISTORICO DAS ANALISES");
                System.out.println("======================");

                List<String> historico =
                        repositorio.listarHistorico();

                for (String linha : historico) {
                    System.out.println(linha);
                }
            }

        } catch (IOException e) {

            System.out.println(
                    "Erro: o arquivo de entrada nao foi encontrado."
            );

        } catch (SQLException e) {

            System.out.println(
                    "Erro ao acessar o banco de dados."
            );

            e.printStackTrace();
        }
    }
}
